### PR TITLE
Added node >= 7.4.0 to engines

### LINKED ISSUE #1: Remove `engines` from package.json or add node.
This module won't install with Yarn- it seems to be more particular about checking these flags than the NPM client. The following error is given:

```
error koa-ssl@2.0.0: The engine "node" is incompatible with this module. Expected version "1.2.0".
```

It can be worked around temporarily by using `yarn --ignore-engines` in your parent application module when installing.

### PR DESCRIPTION
**Pull request by joeyfigaro**
closes #1 

@jclem

### CODE REVIEW

**Comment by d-xo** [comment]
Any reason why this hasn't been merged?

**Comment by jclem** [comment]
I haven’t touched this repository in a long time, and didn’t really realize others were still using it! I’ll take a look this week. 😀

**Comment by jclem** [comment]
Published as v2.0.1. Sorry for the delay!

**Comment by d-xo** [comment]
🎉 🙏 ✨

**Pull request merged**
